*"* components of interface /IWBEP/IF_MGW_ODATA_CMPLX_TYPE
interface /IWBEP/IF_MGW_ODATA_CMPLX_TYPE
  public .


  interfaces /IWBEP/IF_MGW_ODATA_ANNOTATABL .
  interfaces /IWBEP/IF_MGW_ODATA_ITEM .

  aliases CREATE_ANNOTATION
    for /IWBEP/IF_MGW_ODATA_ANNOTATABL~CREATE_ANNOTATION .
  aliases GET_ID
    for /IWBEP/IF_MGW_ODATA_ITEM~GET_ID .
  aliases SET_LABEL_FROM_TEXT_ELEMENT
    for /IWBEP/IF_MGW_ODATA_ITEM~SET_LABEL_FROM_TEXT_ELEMENT .
  aliases SET_NAME
    for /IWBEP/IF_MGW_ODATA_ITEM~SET_NAME .

  types S type CHAR1 .

  methods ADD_AUTO_EXPAND_INCLUDE
    importing
      !IV_INCLUDE_NAME type STRING
      !IV_DUMMY_FIELD type FIELDNAME optional
      !IV_BIND_CONVERSIONS type ABAP_BOOL
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods BIND_STRUCTURE
    importing
      !IV_STRUCTURE_NAME type STRING
      !IV_BIND_CONVERSIONS type ABAP_BOOL default ABAP_FALSE
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods CREATE_CMPLX_TYPE_PROP
    importing
      !IV_PROPERTY_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
      !IV_COMPLEX_TYPE_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
      !IV_ABAP_FIELDNAME type FIELDNAME optional
    returning
      value(RO_COMPLEX_PROP) type ref to /IWBEP/IF_MGW_ODATA_CMPLX_PROP
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods CREATE_COMPLEX_PROPERTY
    importing
      !IV_PROPERTY_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
      !IV_COMPLEX_TYPE_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
      !IV_ABAP_FIELDNAME type FIELDNAME optional
    returning
      value(RO_COMPLEX_TYPE) type ref to /IWBEP/IF_MGW_ODATA_CMPLX_TYPE
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods CREATE_PROPERTY
    importing
      !IV_PROPERTY_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
      !IV_ABAP_FIELDNAME type FIELDNAME optional
      !IV_SOURCE_NAME type STRING optional
    returning
      value(RO_PROPERTY) type ref to /IWBEP/IF_MGW_ODATA_PROPERTY
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods GET_CMPLX_TYPE_PROPERTY
    importing
      !IV_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    returning
      value(RO_COMPLEX_PROPERTY) type ref to /IWBEP/IF_MGW_ODATA_CMPLX_PROP
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods GET_PROPERTIES
    returning
      value(RT_PROPERTIES) type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_T_MGW_ODATA_PROPERTIES .
  methods GET_PROPERTY
    importing
      !IV_PROPERTY_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    returning
      value(RO_PROPERTY) type ref to /IWBEP/IF_MGW_ODATA_PROPERTY
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods SET_BASE_TYPE
    importing
      !IV_ENTITY_TYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods SET_DISABLED
    importing
      !IV_DISABLED type ABAP_BOOL default ABAP_TRUE .
  methods SET_IS_ABSTRACT
    importing
      !IV_IS_ABSTRACT type ABAP_BOOL default ABAP_TRUE .
  methods GET_BASE_TYPE
    returning
      value(RV_BASE_ENTITY_TYPE) type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
endinterface.
