*"* components of interface /IWBEP/IF_MGW_REQ_ENTITY_P
interface /IWBEP/IF_MGW_REQ_ENTITY_P
  public .


  interfaces /IWBEP/IF_MGW_REQ_ENTITY_U .

  aliases GET_CONDITIONAL_INFO
    for /IWBEP/IF_MGW_REQ_ENTITY_U~GET_CONDITIONAL_INFO .
  aliases GET_CONVERTED_KEYS
    for /IWBEP/IF_MGW_REQ_ENTITY_U~GET_CONVERTED_KEYS .
  aliases GET_ENTITY_SET_NAME
    for /IWBEP/IF_MGW_REQ_ENTITY_U~GET_ENTITY_SET_NAME .
  aliases GET_ENTITY_TYPE_NAME
    for /IWBEP/IF_MGW_REQ_ENTITY_U~GET_ENTITY_TYPE_NAME .
  aliases GET_KEYS
    for /IWBEP/IF_MGW_REQ_ENTITY_U~GET_KEYS .

  methods GET_COMPONENTS
    returning
      value(RT_COMPONENTS) type /IWBEP/IF_MGW_APPL_TYPES=>TY_T_COMPONENTS .
endinterface.
